version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: student_mongo
    ports:
      - "8080:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: student_backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: student_frontend
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

volumes:
  mongo-data:
